# Round-5 Pakistani dish expansion. Values are MyFit typical estimates (basis "typical") — recipes and portions vary.
# (id, name, category, serving, unit, grams, kcal, protein, carbs, fat, fiber, aliases, icon description)
D = [
# ---------------- Breads
("khamiri_roti", "Khamiri roti", "Breads", 1, "piece", 90, 250, 7.5, 46, 4, 2.5, ["khameeri roti", "khamiri"], "a round thick leavened khamiri roti, soft and puffy, pale golden with light brown toasted spots and sesame seeds"),
("garlic_naan", "Garlic naan", "Breads", 1, "piece", 110, 330, 9, 52, 9.5, 2, ["lehsan naan", "garlic nan"], "an oval tandoori naan brushed with butter, topped with chopped garlic and green coriander, charred bubbles"),
("aloo_naan", "Aloo naan (stuffed)", "Breads", 1, "piece", 160, 400, 10, 66, 10, 4, ["potato naan", "aloo wala naan"], "a thick round stuffed naan cut open to show spiced yellow mashed potato filling, golden charred surface"),
("chicken_naan", "Chicken naan (stuffed)", "Breads", 1, "piece", 170, 450, 22, 58, 14, 2.5, ["chicken stuffed naan", "murgh naan"], "a thick round stuffed naan cut open to show shredded spiced chicken filling, glossy buttered charred top"),
("rumali_roti", "Rumali roti", "Breads", 1, "piece", 45, 125, 3.5, 24, 1.5, 1, ["roomali roti", "handkerchief roti"], "a paper-thin rumali roti folded like a handkerchief into a soft triangle, pale cream with faint brown spots"),
("missi_roti", "Missi roti", "Breads", 1, "piece", 60, 185, 7, 27, 5.5, 4.5, ["besan roti", "missi"], "a round yellowish missi roti made with gram flour, flecked with green herbs and chilli, toasted spots, butter on top"),
("methi_paratha", "Methi paratha", "Breads", 1, "piece", 90, 280, 6, 36, 12.5, 4, ["fenugreek paratha", "methi wala paratha"], "a round flaky paratha speckled with green fenugreek leaves, golden and glossy with ghee, slightly folded"),
("gobi_paratha", "Gobhi paratha", "Breads", 1, "piece", 140, 340, 8, 48, 13, 5, ["cauliflower paratha", "gobi paratha"], "a thick round stuffed paratha cut in half showing grated spiced cauliflower filling, golden crisp surface"),
("bakarkhani", "Bakarkhani", "Breads", 1, "piece", 60, 260, 4.5, 31, 13, 1, ["baqarkhani", "bakar khani"], "a round flaky layered bakarkhani biscuit-bread, crisp golden spiral layers, sprinkled with sesame seeds"),
("tandoori_paratha", "Tandoori paratha", "Breads", 1, "piece", 110, 330, 7.5, 45, 13, 3, ["tandoori lachha", "tandoor paratha"], "a round tandoori paratha with charred bubbles and visible layers, glistening with butter"),
("daal_paratha", "Chana daal paratha", "Breads", 1, "piece", 140, 360, 11, 50, 13, 6.5, ["daal wala paratha", "lentil paratha"], "a thick round paratha cut open to show yellow spiced chana daal filling, golden crisp surface"),
# ---------------- Rice
("tahiri", "Tahiri (vegetable rice)", "Rice", 1, "plate", 300, 420, 8, 72, 11, 4, ["tehri", "tahari", "aloo tahiri"], "a plate of yellow turmeric tahiri rice with potato cubes, peas and whole spices, steaming"),
("memoni_biryani", "Memoni biryani", "Rice", 1, "plate", 350, 620, 28, 74, 22, 3, ["memon biryani", "kutchi memoni biryani"], "a plate of spicy red-orange memoni biryani with mutton pieces, potato, fried onions and green chilli"),
("tikka_biryani", "Chicken tikka biryani", "Rice", 1, "plate", 350, 600, 32, 72, 19, 2.5, ["tikka biryani"], "a plate of biryani rice layered with charred red chicken tikka chunks, saffron streaks and mint leaves"),
("prawn_biryani", "Prawn biryani", "Rice", 1, "plate", 350, 540, 26, 74, 15, 2.5, ["jheenga biryani", "shrimp biryani"], "a plate of orange-and-white biryani rice with pink curled prawns, fried onions and coriander"),
("egg_biryani", "Egg biryani", "Rice", 1, "plate", 330, 520, 18, 74, 17, 2.5, ["anda biryani"], "a plate of spiced biryani rice with two halved boiled eggs coated in red masala, fried onions on top"),
("sabzi_pulao", "Sabzi pulao", "Rice", 1, "plate", 300, 400, 8, 70, 10, 4.5, ["vegetable pulao", "veg pulao"], "a plate of light brown pulao rice with carrots, peas and green beans, whole spices visible"),
("kashmiri_pulao", "Kashmiri pulao", "Rice", 1, "plate", 300, 470, 8, 76, 15, 3, ["mewa pulao", "dry fruit pulao"], "a plate of pale saffron pulao rice studded with raisins, cashews, almonds and pomegranate seeds"),
# ---------------- Breakfast
("anda_bhurji", "Anda bhurji", "Breakfast", 1, "plate", 150, 260, 15, 5, 20, 1, ["egg bhurji", "scrambled eggs desi", "khagina masala"], "a small plate of spicy scrambled anda bhurji with chopped tomato, onion, green chilli and coriander"),
("kulcha_cholay", "Kulcha cholay", "Breakfast", 1, "plate", 330, 600, 19, 84, 21, 13, ["cholay kulcha", "chole kulche"], "a round fluffy kulcha bread beside a bowl of spicy chickpea cholay topped with onion rings"),
("cheese_omelette", "Cheese omelette", "Breakfast", 1, "piece", 140, 300, 19, 2, 24, 0, ["omelette with cheese"], "a folded golden omelette oozing melted yellow cheese, sprinkled with herbs"),
("khajla", "Khajla (sehri)", "Breakfast", 1, "piece", 60, 300, 4, 30, 18.5, 1, ["khajla pheni", "khajlay"], "a large round crisp flaky khajla pastry, puffed golden layers, dusted with sugar"),
# ---------------- Curries
("chicken_achari", "Achari chicken", "Curries", 1, "bowl", 250, 400, 30, 9, 27, 2, ["achari murgh", "chicken achar"], "a bowl of reddish achari chicken curry with pickling spices, fennel seeds, whole green chillies stuffed with masala"),
("kat_a_kat", "Kat-a-kat (tawa mix)", "Curries", 1, "plate", 250, 450, 30, 6, 34, 1.5, ["takatak", "kata kat", "tak a tak"], "a black iron tawa with finely chopped kidney, brain and liver in spicy masala, green chillies and butter"),
("dum_keema", "Dum keema", "Curries", 1, "bowl", 220, 420, 26, 7, 32, 1.5, ["dum qeema", "smoked keema"], "a bowl of dark brown smoky minced meat dum keema with fried onions, ginger slivers and green chilli"),
("chicken_bhuna", "Bhuna chicken", "Curries", 1, "bowl", 250, 380, 32, 8, 24, 2, ["bhuna murgh", "chicken bhuna masala"], "a bowl of thick dry dark-red bhuna chicken masala, chicken pieces coated in caramelised onion-tomato masala"),
("mutton_dopiaza", "Mutton do pyaza", "Curries", 1, "bowl", 250, 470, 27, 12, 35, 2.5, ["gosht do pyaza", "mutton dopiaza"], "a bowl of mutton curry with lots of large onion petals, brown gravy, whole spices"),
("chicken_dopiaza", "Chicken do pyaza", "Curries", 1, "bowl", 250, 370, 30, 12, 22, 2.5, ["murgh do pyaza", "chicken dopiaza"], "a bowl of chicken curry with lots of large onion petals and orange-brown gravy"),
("sindhi_kadhi", "Sindhi kadhi", "Curries", 1, "bowl", 300, 230, 7, 26, 11, 6, ["sindhi karhi"], "a bowl of thin yellow-orange tangy sindhi kadhi with drumstick pods, okra, potato and vegetables"),
("murgh_cholay", "Murgh cholay", "Curries", 1, "bowl", 280, 430, 29, 32, 20, 9, ["murgh chanay", "lahori murgh cholay", "chicken chickpeas"], "a bowl of chicken and chickpea curry in rich brown gravy, topped with ginger slivers and coriander"),
("saag_gosht", "Saag gosht", "Curries", 1, "bowl", 250, 420, 25, 9, 32, 4, ["palak saag gosht", "sarson gosht"], "a bowl of dark green mustard-spinach saag with tender mutton chunks and a swirl of butter"),
("methi_gosht", "Methi gosht", "Curries", 1, "bowl", 250, 440, 26, 8, 34, 3, ["methi mutton", "fenugreek mutton"], "a bowl of mutton curry with dark green fenugreek leaves in brown masala gravy"),
("matar_gosht", "Matar gosht", "Curries", 1, "bowl", 250, 430, 26, 14, 30, 4.5, ["mutton peas", "gosht matar"], "a bowl of mutton curry with green peas in orange-brown gravy"),
("chicken_palak", "Palak chicken", "Curries", 1, "bowl", 250, 330, 30, 8, 20, 3.5, ["palak murgh", "spinach chicken"], "a bowl of creamy dark green spinach gravy with chicken pieces and a swirl of cream"),
("nargisi_kofta", "Nargisi kofta", "Curries", 1, "bowl", 250, 480, 28, 10, 36, 2, ["nargisi koftay", "egg kofta"], "a bowl of curry with halved nargisi koftas showing boiled egg wrapped in minced meat, rich red gravy"),
("chicken_stew", "Chicken stew (desi)", "Curries", 1, "bowl", 300, 340, 28, 18, 17, 4, ["murgh stew", "chicken vegetable stew"], "a bowl of chicken stew with potatoes, carrots and peas in light brown gravy, black pepper"),
("mutton_stew", "Mutton stew (desi)", "Curries", 1, "bowl", 300, 430, 27, 18, 28, 4, ["gosht stew"], "a bowl of mutton stew with potatoes and carrots in a peppery brown gravy"),
# ---------------- BBQ & Kebabs
("dhaga_kebab", "Dhaga kebab", "BBQ & Kebabs", 4, "piece", 160, 420, 24, 6, 33, 1, ["dhaagay wala kebab", "thread kebab"], "four soft long beef dhaga kebabs wrapped with thin threads on a plate with onion rings and lemon"),
("charsi_tikka", "Charsi tikka (lamb)", "BBQ & Kebabs", 6, "piece", 200, 520, 34, 1, 42, 0, ["charsi tikka", "peshawari tikka", "namak mandi tikka"], "a skewer of juicy lamb tikka cubes alternating with lamb fat pieces, salt-and-pepper charred"),
("galouti_kebab", "Galouti kebab", "BBQ & Kebabs", 4, "piece", 160, 440, 22, 8, 35, 1, ["galawati kebab", "galauti"], "four round flat melt-in-mouth galouti kebab patties, browned edges, onion rings and mint chutney"),
("kalmi_tikka", "Kalmi tikka", "BBQ & Kebabs", 2, "piece", 220, 400, 40, 4, 25, 0.5, ["kalmi kebab", "chicken leg tikka"], "two charred orange-red chicken leg kalmi tikka pieces with bone handle, lemon wedge and onion rings"),
("hariyali_tikka", "Hariyali chicken tikka", "BBQ & Kebabs", 8, "piece", 200, 330, 40, 5, 16, 1.5, ["green tikka", "hariyali boti"], "a skewer of green mint-coriander marinated chicken tikka chunks, charred edges"),
("sajji_full", "Sajji (whole chicken with rice)", "BBQ & Kebabs", 1, "plate", 900, 1700, 130, 130, 72, 3, ["balochi sajji", "full sajji", "sajji"], "a whole roasted salted sajji chicken split open on a bed of rice, golden skin, lemon wedges"),
# ---------------- Street food
("kachaloo_chaat", "Kachaloo chaat", "Street food", 1, "bowl", 200, 190, 3, 42, 1, 4, ["kachalu chaat", "arvi chaat"], "a bowl of tangy kachaloo chaat cubes with lemon, chilli flakes and chaat masala, toothpicks"),
("corn_chaat", "Corn chaat", "Street food", 1, "cup", 180, 220, 6, 34, 7, 4, ["bhutta chaat", "sweet corn chaat"], "a paper cup of butter sweet corn chaat with lemon, chilli and chaat masala, small spoon"),
("dahi_puri", "Dahi puri", "Street food", 6, "piece", 180, 300, 8, 42, 11, 4, ["dahi gol gappay", "dahi phulki"], "six crisp round puris filled with potato, chickpeas, yogurt, tamarind chutney and sev on a plate"),
("zinger_roll", "Zinger paratha roll", "Street food", 1, "roll", 260, 680, 26, 62, 36, 3, ["zinger roll", "zinger paratha"], "a paratha roll wrapped in paper, filled with crispy fried chicken, lettuce and mayo sauce"),
("malai_boti_roll", "Malai boti roll", "Street food", 1, "roll", 240, 560, 28, 48, 28, 2.5, ["malai roll", "boti roll"], "a paratha roll wrapped in paper with creamy white malai boti chunks, onions and green chutney"),
("fish_pakora", "Fish pakora", "Street food", 1, "plate", 200, 420, 30, 20, 24, 2, ["machli pakora", "lahori fish pakora"], "a plate of orange-red crispy battered fish pakora pieces with lemon wedges and chutney"),
("samosa_chaat", "Samosa chaat", "Street food", 1, "plate", 280, 480, 13, 58, 22, 10, ["samosa chole chaat"], "a plate of broken samosas topped with chickpea cholay, yogurt, tamarind and green chutney, onions"),
# ---------------- Sweets
("rabri", "Rabri", "Sweets", 1, "bowl", 120, 300, 9, 30, 16, 0, ["rabdi", "rabri doodh"], "a small clay bowl of thick creamy rabri with layers of milk skin, saffron, pistachio slivers"),
("chum_chum", "Chum chum", "Sweets", 2, "piece", 80, 280, 6, 44, 9, 0, ["cham cham"], "two oval pink and white chum chum sweets coated in grated coconut and khoya"),
("nan_khatai", "Nan khatai", "Sweets", 2, "piece", 40, 210, 3, 22, 12.5, 0.5, ["naan khatai", "nankhatai"], "two round domed golden nan khatai biscuits with cracked tops and a pistachio in the centre"),
("shakarpara", "Shakarpara", "Sweets", 1, "cup", 50, 250, 3, 30, 13, 0.5, ["shakar paray", "shakarparay"], "a small bowl of diamond-shaped crunchy fried shakarpara coated in white sugar glaze"),
("lab_e_shireen", "Lab-e-shireen", "Sweets", 1, "bowl", 180, 330, 7, 46, 13, 1.5, ["labe shireen", "lab e shireen"], "a glass bowl of creamy custard lab-e-shireen with colourful jelly cubes, fruit and vermicelli"),
("malpura", "Malpura", "Sweets", 2, "piece", 100, 380, 6, 48, 18, 1, ["malpuray", "malpua"], "two round golden fried malpura pancakes soaked in syrup, topped with rabri and pistachio"),
("pheni", "Pheni with milk", "Sweets", 1, "bowl", 220, 380, 10, 46, 17, 1, ["phenian", "doodh pheni", "feni"], "a bowl of fine crispy pheni vermicelli nest soaked in sweet milk, sprinkled with almonds"),
("anday_ka_halwa", "Anday ka halwa", "Sweets", 1, "bowl", 120, 460, 11, 44, 27, 0.5, ["egg halwa"], "a small bowl of golden-yellow grainy egg halwa garnished with almonds and pistachios"),
("badam_halwa", "Badam halwa", "Sweets", 1, "bowl", 100, 480, 10, 40, 31, 4, ["almond halwa"], "a small bowl of rich orange-golden badam halwa with ghee shine, almond slivers on top"),
("chikki", "Gur chikki", "Sweets", 1, "piece", 40, 200, 5.5, 22, 10, 2, ["peanut chikki", "gajak", "til chikki"], "a rectangular piece of brown peanut and jaggery chikki brittle, glossy"),
("dodha_barfi", "Dodha barfi", "Sweets", 1, "piece", 50, 210, 5, 26, 10, 1, ["dhodha", "khushab dodha", "doda"], "a square piece of dark brown grainy dodha barfi with nuts on top"),
("balushahi", "Balushahi", "Sweets", 1, "piece", 60, 260, 2.5, 34, 13, 0.5, ["badusha", "balu shahi"], "a round glazed flaky balushahi with a dimple in the centre, shiny sugar coating"),
("kalakand", "Kalakand", "Sweets", 1, "piece", 50, 180, 6, 21, 8, 0, ["kalaqand"], "a square moist white grainy kalakand milk sweet topped with pistachio slivers"),
("panjiri", "Panjiri", "Sweets", 1, "bowl", 60, 320, 6, 32, 19, 3, ["panjeeri"], "a small bowl of golden toasted wheat flour panjiri mixed with nuts, makhana and dry fruit"),
("pinni", "Pinni", "Sweets", 1, "piece", 50, 240, 4.5, 24, 14, 2, ["pinniyan", "atta pinni"], "two round brown atta pinni balls with almonds and ghee shine"),
("til_ladoo", "Til ladoo", "Sweets", 1, "piece", 30, 150, 4, 14, 9, 2.5, ["sesame ladoo", "tilkut"], "two round sesame seed and jaggery til ladoos"),
("meethi_boondi", "Meethi boondi", "Sweets", 1, "cup", 60, 260, 3.5, 36, 11.5, 1, ["boondi", "sweet boondi"], "a small bowl of tiny round orange sweet boondi pearls glistening with syrup"),
("gur_wale_chawal", "Gur wale chawal", "Sweets", 1, "plate", 200, 400, 5, 72, 10, 1.5, ["jaggery rice", "gurh walay chawal"], "a plate of brown jaggery sweet rice with fennel seeds, coconut flakes and almonds"),
# ---------------- Drinks
("doodh_soda", "Doodh soda", "Drinks", 1, "glass", 300, 150, 5, 22, 4.5, 0, ["milk soda", "dudh soda"], "a tall glass of fizzy white doodh soda with bubbles and ice cubes"),
("kahwa", "Kahwa (sweetened)", "Drinks", 1, "cup", 200, 30, 0, 7.5, 0, 0, ["qehwa", "peshawari kahwa", "kehwa"], "a small glass cup of golden-green kahwa tea with cardamom pods and a slice of lemon"),
("haldi_doodh", "Haldi doodh", "Drinks", 1, "glass", 250, 170, 8, 15, 8.5, 0, ["turmeric milk", "haldi wala doodh"], "a glass of warm golden turmeric haldi milk with a sprinkle of cinnamon"),
("thadal", "Thadal (Sindhi)", "Drinks", 1, "glass", 250, 260, 7, 32, 12, 1, ["thandai", "sindhi thadal", "sardai"], "a tall glass of creamy pale thadal drink with almonds, rose petals and fennel"),
("jaljeera", "Jaljeera", "Drinks", 1, "glass", 250, 40, 0.5, 10, 0, 0.5, ["jal jeera"], "a glass of tangy dark brown jaljeera with mint leaves, lemon slice and crunchy boondi on top"),
("kanji", "Kanji (black carrot)", "Drinks", 1, "glass", 250, 35, 0.5, 8, 0, 1, ["kaanji", "gajar kanji"], "a glass of deep purple fermented black carrot kanji drink with carrot sticks"),
("mango_lassi", "Mango lassi", "Drinks", 1, "glass", 300, 270, 8, 46, 6, 1, ["aam lassi"], "a tall glass of thick orange mango lassi with a slice of mango on the rim"),
("khajoor_shake", "Khajoor shake", "Drinks", 1, "glass", 300, 340, 10, 58, 8, 3.5, ["date shake", "dates milkshake"], "a tall glass of light brown date milkshake with chopped dates on top"),
("chikoo_shake", "Chikoo shake", "Drinks", 1, "glass", 300, 300, 8, 50, 7.5, 4, ["sapota shake", "chiku shake"], "a tall glass of beige chikoo milkshake with a cut chikoo fruit beside it"),
# ---------------- Snacks & Nuts
("makhana", "Roasted makhana", "Snacks & Nuts", 1, "cup", 30, 110, 3.5, 20, 1.5, 4, ["phool makhana", "fox nuts", "lotus seeds"], "a small bowl of white roasted puffed makhana lotus seeds lightly spiced"),
("namak_pare", "Namak pare", "Snacks & Nuts", 1, "cup", 50, 260, 4, 28, 14.5, 1, ["namak paray", "nimki"], "a small bowl of crunchy diamond-shaped savoury namak pare with ajwain"),
("mathri", "Mathri", "Snacks & Nuts", 2, "piece", 40, 210, 3, 22, 12, 1, ["mathi", "mathiyan"], "two round flaky golden mathri crackers with fork pricks and ajwain seeds"),
("chana_jor_garam", "Chana jor garam", "Snacks & Nuts", 1, "cup", 50, 190, 9, 28, 5, 7, ["chana chor garam", "flattened chana"], "a paper cone of flattened spicy chana jor garam chickpeas with onion, lemon and chilli"),
("cake_rusk", "Cake rusk", "Snacks & Nuts", 2, "piece", 40, 180, 3, 26, 7, 0.5, ["cake rus", "bakery rusk"], "two long golden twice-baked cake rusks with a crunchy texture"),
# ---------------- Vegetables
("aloo_baingan", "Aloo baingan", "Vegetables", 1, "bowl", 200, 190, 3.5, 22, 10, 6, ["baingan aloo", "eggplant potato"], "a bowl of aloo baingan curry with potato cubes and soft purple eggplant in tomato masala"),
("aloo_shimla_mirch", "Aloo shimla mirch", "Vegetables", 1, "bowl", 200, 180, 3.5, 22, 9, 4.5, ["capsicum aloo", "shimla mirch aloo"], "a bowl of stir-fried potato cubes with green capsicum strips and spices"),
("kaddu", "Kaddu (sweet pumpkin)", "Vegetables", 1, "bowl", 200, 150, 2.5, 20, 7, 4, ["kaddu ki sabzi", "sitaphal", "pumpkin curry"], "a bowl of orange sweet-and-sour pumpkin kaddu sabzi with fenugreek seeds and coriander"),
("aloo_methi", "Aloo methi", "Vegetables", 1, "bowl", 200, 190, 4, 23, 9, 5, ["methi aloo"], "a bowl of potato cubes stir-fried with dark green fenugreek leaves"),
("kachnar", "Kachnar ki sabzi", "Vegetables", 1, "bowl", 200, 160, 4, 14, 10, 6, ["kachnar", "kachnar gosht"], "a bowl of kachnar flower bud sabzi, green buds in brown masala with onions"),
("gajar_matar", "Gajar matar", "Vegetables", 1, "bowl", 200, 160, 4.5, 18, 8, 6, ["carrot peas", "matar gajar"], "a bowl of diced orange carrots and green peas stir-fried with cumin"),
("aloo_tamatar", "Aloo tamatar", "Vegetables", 1, "bowl", 220, 200, 3.5, 26, 9, 4, ["aloo tamatar ki sabzi", "potato tomato curry"], "a bowl of thin red tomato gravy with soft potato cubes and coriander"),
("sem_phali", "Sem ki phali", "Vegetables", 1, "bowl", 200, 140, 4, 13, 8, 6, ["green beans", "phaliyan", "french beans"], "a bowl of stir-fried green beans cut into short pieces with spices"),
("mooli_bhujia", "Mooli bhujia", "Vegetables", 1, "bowl", 180, 120, 2.5, 10, 8, 4, ["mooli ki bhujia", "radish sabzi"], "a bowl of grated white radish and green leaves stir-fried with spices"),
# ---------------- Daal & Beans
("daal_palak", "Daal palak", "Daal & Beans", 1, "bowl", 250, 230, 12, 28, 8, 9, ["palak daal", "spinach daal"], "a bowl of yellow lentil daal mixed with green spinach, tempered with garlic and red chilli"),
("lauki_chana_daal", "Lauki chana daal", "Daal & Beans", 1, "bowl", 250, 240, 11, 30, 8.5, 9, ["kaddu chana daal", "ghiya daal"], "a bowl of yellow chana daal with pale green bottle gourd chunks and tadka"),
# ---------------- Regional (KPK, Balochistan, Sindh, GB, AJK)
("chapshoro", "Chapshoro (GB meat pie)", "Regional", 1, "piece", 220, 560, 26, 52, 27, 3, ["chap shuro", "hunza pizza", "gilgiti chapshoro"], "a round golden flatbread meat pie chapshoro cut into wedges showing minced meat, onion and chilli filling"),
("mantu", "Mantu (steamed dumplings)", "Regional", 6, "piece", 200, 380, 20, 40, 15, 3, ["mantoo", "mantu dumplings"], "six steamed mantu dumplings filled with minced meat, topped with yogurt, lentil sauce and dried mint"),
("bolani", "Bolani", "Regional", 1, "piece", 150, 360, 8, 46, 16, 4, ["bolani kachalu", "boulani"], "a half-moon shaped crisp bolani flatbread filled with potato and green onion, golden fried"),
("kashmiri_harissa", "Kashmiri harissa", "Regional", 1, "bowl", 250, 520, 30, 18, 36, 3, ["harissa", "hareesa"], "a clay bowl of smooth pounded mutton harissa topped with sizzling ghee and crisp fried onions"),
("goshtaba", "Goshtaba", "Regional", 3, "piece", 280, 520, 32, 10, 39, 0.5, ["gushtaba", "kashmiri goshtaba"], "three large pounded meatballs in creamy white yogurt gravy with dried mint"),
("rista", "Rista", "Regional", 3, "piece", 250, 470, 30, 7, 36, 1, ["kashmiri rista"], "three round pounded meatballs in a bright red kashmiri chilli gravy"),
("sai_bhaji", "Sai bhaji", "Regional", 1, "bowl", 250, 240, 11, 28, 9, 9, ["sindhi sai bhaji", "sae bhaji"], "a bowl of green sindhi sai bhaji of spinach, lentils and vegetables, mashed and thick"),
("koki", "Koki (Sindhi)", "Regional", 1, "piece", 90, 330, 6.5, 38, 17, 3, ["sindhi koki", "kokee"], "a round thick crisp sindhi koki flatbread with flecks of onion, green chilli and coriander"),
("seyal_phulka", "Seyal phulka", "Regional", 1, "plate", 200, 330, 8, 42, 14, 4, ["sayal phulka", "sindhi seyal maani"], "a plate of torn chapati pieces cooked in spicy tomato masala, sindhi seyal phulka, coriander on top"),
("bhee_curry", "Bhee (lotus stem) curry", "Regional", 1, "bowl", 220, 210, 4, 24, 11, 6, ["bhee", "kamal kakri", "lotus stem"], "a bowl of lotus stem slices with visible hole patterns in tomato masala gravy"),
("khaddi_kebab", "Khaddi kebab (Balochi lamb)", "Regional", 1, "plate", 250, 600, 50, 0, 44, 0, ["khaddi kabab", "balochi khaddi"], "slow pit-roasted lamb pieces khaddi kebab, crisp brown outside, on a plate with lemon and onion"),
("sohbat", "Sohbat (Balochi)", "Regional", 1, "bowl", 350, 520, 30, 50, 22, 3, ["sobat", "balochi sohbat"], "a wide bowl of bread pieces soaked in rich mutton broth with meat chunks on top"),
("kaak", "Kaak (Balochi rock bread)", "Regional", 1, "piece", 120, 320, 9, 62, 3, 3, ["kak", "balochi kaak"], "a thick round dense kaak bread with brown baked crust and stone marks"),
("rosh", "Rosh (Namkeen gosht)", "Regional", 1, "bowl", 300, 450, 32, 4, 34, 0.5, ["landi rosh", "rosh gosht"], "a bowl of simple salted lamb chunks on the bone in clear fatty broth with a whole onion"),
]
